// #included from color.h

#include "color.h" // make intellisense happy

// From https://www.w3schools.com/colors/colors_names.asp
// "Color Names Supported by All Browsers"
// Some editing by Claude, some by me.

// clang-format off
static constexpr Color black()                   { return Color(0x00, 0x00, 0x00); }
static constexpr Color navy()                    { return Color(0x00, 0x00, 0x80); }
static constexpr Color dark_blue()               { return Color(0x00, 0x00, 0x8b); }
static constexpr Color medium_blue()             { return Color(0x00, 0x00, 0xcd); }
static constexpr Color blue()                    { return Color(0x00, 0x00, 0xff); }
static constexpr Color dark_green()              { return Color(0x00, 0x64, 0x00); }
static constexpr Color green()                   { return Color(0x00, 0x80, 0x00); }
static constexpr Color teal()                    { return Color(0x00, 0x80, 0x80); }
static constexpr Color dark_cyan()               { return Color(0x00, 0x8b, 0x8b); }
static constexpr Color deep_sky_blue()           { return Color(0x00, 0xbf, 0xff); }
static constexpr Color dark_turquoise()          { return Color(0x00, 0xce, 0xd1); }
static constexpr Color medium_spring_green()     { return Color(0x00, 0xfa, 0x9a); }
static constexpr Color lime()                    { return Color(0x00, 0xff, 0x00); }
static constexpr Color spring_green()            { return Color(0x00, 0xff, 0x7f); }
static constexpr Color aqua()                    { return Color(0x00, 0xff, 0xff); }
static constexpr Color cyan()                    { return Color(0x00, 0xff, 0xff); }
static constexpr Color midnight_blue()           { return Color(0x19, 0x19, 0x70); }
static constexpr Color dodger_blue()             { return Color(0x1e, 0x90, 0xff); }
static constexpr Color light_sea_green()         { return Color(0x20, 0xb2, 0xaa); }
static constexpr Color forest_green()            { return Color(0x22, 0x8b, 0x22); }
static constexpr Color sea_green()               { return Color(0x2e, 0x8b, 0x57); }
static constexpr Color dark_slate_gray()         { return Color(0x2f, 0x4f, 0x4f); }
static constexpr Color dark_slate_grey()         { return Color(0x2f, 0x4f, 0x4f); }
static constexpr Color lime_green()              { return Color(0x32, 0xcd, 0x32); }
static constexpr Color medium_sea_green()        { return Color(0x3c, 0xb3, 0x71); }
static constexpr Color turquoise()               { return Color(0x40, 0xe0, 0xd0); }
static constexpr Color royal_blue()              { return Color(0x41, 0x69, 0xe1); }
static constexpr Color steel_blue()              { return Color(0x46, 0x82, 0xb4); }
static constexpr Color dark_slate_blue()         { return Color(0x48, 0x3d, 0x8b); }
static constexpr Color medium_turquoise()        { return Color(0x48, 0xd1, 0xcc); }
static constexpr Color indigo()                  { return Color(0x4b, 0x00, 0x82); }
static constexpr Color dark_olive_green()        { return Color(0x55, 0x6b, 0x2f); }
static constexpr Color cadet_blue()              { return Color(0x5f, 0x9e, 0xa0); }
static constexpr Color cornflower_blue()         { return Color(0x64, 0x95, 0xed); }
static constexpr Color rebecca_purple()          { return Color(0x66, 0x33, 0x99); }
static constexpr Color medium_aqua_marine()      { return Color(0x66, 0xcd, 0xaa); }
static constexpr Color dim_gray()                { return Color(0x69, 0x69, 0x69); }
static constexpr Color dim_grey()                { return Color(0x69, 0x69, 0x69); }
static constexpr Color slate_blue()              { return Color(0x6a, 0x5a, 0xcd); }
static constexpr Color olive_drab()              { return Color(0x6b, 0x8e, 0x23); }
static constexpr Color slate_gray()              { return Color(0x70, 0x80, 0x90); }
static constexpr Color slate_grey()              { return Color(0x70, 0x80, 0x90); }
static constexpr Color light_slate_gray()        { return Color(0x77, 0x88, 0x99); }
static constexpr Color light_slate_grey()        { return Color(0x77, 0x88, 0x99); }
static constexpr Color medium_slate_blue()       { return Color(0x7b, 0x68, 0xee); }
static constexpr Color lawn_green()              { return Color(0x7c, 0xfc, 0x00); }
static constexpr Color chartreuse()              { return Color(0x7f, 0xff, 0x00); }
static constexpr Color aquamarine()              { return Color(0x7f, 0xff, 0xd4); }
static constexpr Color maroon()                  { return Color(0x80, 0x00, 0x00); }
static constexpr Color purple()                  { return Color(0x80, 0x00, 0x80); }
static constexpr Color olive()                   { return Color(0x80, 0x80, 0x00); }
static constexpr Color gray()                    { return Color(0x80, 0x80, 0x80); }
static constexpr Color grey()                    { return Color(0x80, 0x80, 0x80); }
static constexpr Color sky_blue()                { return Color(0x87, 0xce, 0xeb); }
static constexpr Color light_sky_blue()          { return Color(0x87, 0xce, 0xfa); }
static constexpr Color blue_violet()             { return Color(0x8a, 0x2b, 0xe2); }
static constexpr Color dark_red()                { return Color(0x8b, 0x00, 0x00); }
static constexpr Color dark_magenta()            { return Color(0x8b, 0x00, 0x8b); }
static constexpr Color saddle_brown()            { return Color(0x8b, 0x45, 0x13); }
static constexpr Color dark_sea_green()          { return Color(0x8f, 0xbc, 0x8f); }
static constexpr Color light_green()             { return Color(0x90, 0xee, 0x90); }
static constexpr Color medium_purple()           { return Color(0x93, 0x70, 0xdb); }
static constexpr Color dark_violet()             { return Color(0x94, 0x00, 0xd3); }
static constexpr Color pale_green()              { return Color(0x98, 0xfb, 0x98); }
static constexpr Color dark_orchid()             { return Color(0x99, 0x32, 0xcc); }
static constexpr Color yellow_green()            { return Color(0x9a, 0xcd, 0x32); }
static constexpr Color sienna()                  { return Color(0xa0, 0x52, 0x2d); }
static constexpr Color brown()                   { return Color(0xa5, 0x2a, 0x2a); }
static constexpr Color dark_gray()               { return Color(0xa9, 0xa9, 0xa9); }
static constexpr Color dark_grey()               { return Color(0xa9, 0xa9, 0xa9); }
static constexpr Color light_blue()              { return Color(0xad, 0xd8, 0xe6); }
static constexpr Color green_yellow()            { return Color(0xad, 0xff, 0x2f); }
static constexpr Color pale_turquoise()          { return Color(0xaf, 0xee, 0xee); }
static constexpr Color light_steel_blue()        { return Color(0xb0, 0xc4, 0xde); }
static constexpr Color powder_blue()             { return Color(0xb0, 0xe0, 0xe6); }
static constexpr Color fire_brick()              { return Color(0xb2, 0x22, 0x22); }
static constexpr Color dark_golden_rod()         { return Color(0xb8, 0x86, 0x0b); }
static constexpr Color medium_orchid()           { return Color(0xba, 0x55, 0xd3); }
static constexpr Color rosy_brown()              { return Color(0xbc, 0x8f, 0x8f); }
static constexpr Color dark_khaki()              { return Color(0xbd, 0xb7, 0x6b); }
static constexpr Color silver()                  { return Color(0xc0, 0xc0, 0xc0); }
static constexpr Color medium_violet_red()       { return Color(0xc7, 0x15, 0x85); }
static constexpr Color indian_red()              { return Color(0xcd, 0x5c, 0x5c); }
static constexpr Color peru()                    { return Color(0xcd, 0x85, 0x3f); }
static constexpr Color chocolate()               { return Color(0xd2, 0x69, 0x1e); }
static constexpr Color tan()                     { return Color(0xd2, 0xb4, 0x8c); }
static constexpr Color light_gray()              { return Color(0xd3, 0xd3, 0xd3); }
static constexpr Color light_grey()              { return Color(0xd3, 0xd3, 0xd3); }
static constexpr Color thistle()                 { return Color(0xd8, 0xbf, 0xd8); }
static constexpr Color orchid()                  { return Color(0xda, 0x70, 0xd6); }
static constexpr Color golden_rod()              { return Color(0xda, 0xa5, 0x20); }
static constexpr Color pale_violet_red()         { return Color(0xdb, 0x70, 0x93); }
static constexpr Color crimson()                 { return Color(0xdc, 0x14, 0x3c); }
static constexpr Color gainsboro()               { return Color(0xdc, 0xdc, 0xdc); }
static constexpr Color plum()                    { return Color(0xdd, 0xa0, 0xdd); }
static constexpr Color burly_wood()              { return Color(0xde, 0xb8, 0x87); }
static constexpr Color light_cyan()              { return Color(0xe0, 0xff, 0xff); }
static constexpr Color lavender()                { return Color(0xe6, 0xe6, 0xfa); }
static constexpr Color dark_salmon()             { return Color(0xe9, 0x96, 0x7a); }
static constexpr Color violet()                  { return Color(0xee, 0x82, 0xee); }
static constexpr Color pale_golden_rod()         { return Color(0xee, 0xe8, 0xaa); }
static constexpr Color light_coral()             { return Color(0xf0, 0x80, 0x80); }
static constexpr Color khaki()                   { return Color(0xf0, 0xe6, 0x8c); }
static constexpr Color alice_blue()              { return Color(0xf0, 0xf8, 0xff); }
static constexpr Color honey_dew()               { return Color(0xf0, 0xff, 0xf0); }
static constexpr Color azure()                   { return Color(0xf0, 0xff, 0xff); }
static constexpr Color sandy_brown()             { return Color(0xf4, 0xa4, 0x60); }
static constexpr Color wheat()                   { return Color(0xf5, 0xde, 0xb3); }
static constexpr Color beige()                   { return Color(0xf5, 0xf5, 0xdc); }
static constexpr Color white_smoke()             { return Color(0xf5, 0xf5, 0xf5); }
static constexpr Color mint_cream()              { return Color(0xf5, 0xff, 0xfa); }
static constexpr Color ghost_white()             { return Color(0xf8, 0xf8, 0xff); }
static constexpr Color salmon()                  { return Color(0xfa, 0x80, 0x72); }
static constexpr Color antique_white()           { return Color(0xfa, 0xeb, 0xd7); }
static constexpr Color linen()                   { return Color(0xfa, 0xf0, 0xe6); }
static constexpr Color light_golden_rod_yellow() { return Color(0xfa, 0xfa, 0xd2); }
static constexpr Color old_lace()                { return Color(0xfd, 0xf5, 0xe6); }
static constexpr Color red()                     { return Color(0xff, 0x00, 0x00); }
static constexpr Color fuchsia()                 { return Color(0xff, 0x00, 0xff); }
static constexpr Color magenta()                 { return Color(0xff, 0x00, 0xff); }
static constexpr Color deep_pink()               { return Color(0xff, 0x14, 0x93); }
static constexpr Color orange_red()              { return Color(0xff, 0x45, 0x00); }
static constexpr Color tomato()                  { return Color(0xff, 0x63, 0x47); }
static constexpr Color hot_pink()                { return Color(0xff, 0x69, 0xb4); }
static constexpr Color coral()                   { return Color(0xff, 0x7f, 0x50); }
static constexpr Color dark_orange()             { return Color(0xff, 0x8c, 0x00); }
static constexpr Color light_salmon()            { return Color(0xff, 0xa0, 0x7a); }
static constexpr Color orange()                  { return Color(0xff, 0xa5, 0x00); }
static constexpr Color light_pink()              { return Color(0xff, 0xb6, 0xc1); }
static constexpr Color pink()                    { return Color(0xff, 0xc0, 0xcb); }
static constexpr Color gold()                    { return Color(0xff, 0xd7, 0x00); }
static constexpr Color peach_puff()              { return Color(0xff, 0xda, 0xb9); }
static constexpr Color navajo_white()            { return Color(0xff, 0xde, 0xad); }
static constexpr Color moccasin()                { return Color(0xff, 0xe4, 0xb5); }
static constexpr Color bisque()                  { return Color(0xff, 0xe4, 0xc4); }
static constexpr Color misty_rose()              { return Color(0xff, 0xe4, 0xe1); }
static constexpr Color blanched_almond()         { return Color(0xff, 0xeb, 0xcd); }
static constexpr Color papaya_whip()             { return Color(0xff, 0xef, 0xd5); }
static constexpr Color lavender_blush()          { return Color(0xff, 0xf0, 0xf5); }
static constexpr Color sea_shell()               { return Color(0xff, 0xf5, 0xee); }
static constexpr Color cornsilk()                { return Color(0xff, 0xf8, 0xdc); }
static constexpr Color lemon_chiffon()           { return Color(0xff, 0xfa, 0xcd); }
static constexpr Color floral_white()            { return Color(0xff, 0xfa, 0xf0); }
static constexpr Color snow()                    { return Color(0xff, 0xfa, 0xfa); }
static constexpr Color yellow()                  { return Color(0xff, 0xff, 0x00); }
static constexpr Color light_yellow()            { return Color(0xff, 0xff, 0xe0); }
static constexpr Color ivory()                   { return Color(0xff, 0xff, 0xf0); }
static constexpr Color white()                   { return Color(0xff, 0xff, 0xff); }
// clang-format off
